config/routes.rb
Rails.application.routes.draw do
  root "news_articles#index"
  devise_for :users
  resources:categorys
  resources:news_articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many:news_articles
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
  belongs_to :category
  has_one_attached :avatar
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
  def index
    @categorys = Category.all
  end

  def new
    @category = Category.new
  end


  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categorys_path
    else
      render :new
    end
  end


def edit 
@category = Category.find(params[:id])
end

def update
@category = Category.find(params[:id])

if @category.update(category_params)
  redirect_to @category
else
render :index
end
end

def destroy
  @category = Category.find(params[:id])
  if @category.destroy
    redirect_to categorys_path
  else
    render :index
  end
end


private
def category_params
  params.require(:category).permit(:name)
end
end

app/controllers/news_articles_controller.rb
class NewsArticlesController < ApplicationController
  def index
    @news_articles = NewsArticle.all
  end

  def new 
   @news_article = NewsArticle.new
  end


  def create
    @news_article = NewsArticle.new(news_article_params)

    if @news_article.save
      redirect_to @news_article
    else
      render 'new'
    end
  end


def edit 
@news_article =NewsArticle.find(params[:id])
end

def update
@news_article = NewsArticle.find(params[:id])

if @news_article.update(news_article_params)
  redirect_to @news_article
else
render :index
end
end

def destroy
  @news_article = NewsArticle.find(params[:id])
  if @news_article.destroy
    redirect_to news_articles_path
  else
    render :index
  end
end


private
def news_article_params
  params.require(:news_article).permit(:title, :sub_topic, :content, :category_id)
end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  GET /resource/sign_up
  def new
    super
  end

  POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    resource.add_role params[:User][:roles]
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/news_articles_helper.rb
module NewsArticlesHelper
end

app/views/categorys/edit.html.erb
<h1>Edit category</h1>

<%= link_to "show category",  categorys_path %>

<%= form_with model:  @category do |form|%>
        <div>
          <%= form.label :name %><br>
          <%= form.text_field :name %>
        </div>
      
       

        <div>
          <%= form.submit %>
        </div>

    <% end %>

app/views/categorys/index.html.erb
<h1>Category LISTS</h1>

<button><%= link_to "create new category",  new_category_path %></button>

<% @categorys.each do |category|%>
<ul>
<li><%= category.name%></li>
</ul>

<button><%= link_to "Delete", category_path(category), method: :delete, data: { turbo_method: :delete, confirm: "Are you sure?" } %></button>
<button><%= link_to "Edit",   edit_category_path(category) %>
</button>
<% end %>

app/views/categorys/new.html.erb
<h1>my form</h1>

<button>
<%= link_to "show category",  categorys_path %></button>

<%= form_with model: @category do |form|%>
    <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

        <div>
         <button> <%= form.submit %></button>
        </div>

    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>

  <body>
</div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/news_articles/edit.html.erb
<h1>Edit articles</h1>

<%= link_to "show news_article",  news_articles_path %>

<%= form_with model: @news_article do |form|%>
        <div>
          <%= form.label :Tittle %><br>
          <%= form.text_field :title %>
        </div>
      
        <div>
          <%= form.label :Sub_topic %><br>
          <%= form.text_field :sub_topic %>
        </div>

        <div>
        <%= form.label :Content %><br>
        <%= form.text_field :content %>
      </div>

      <div>
      <%= form.label :image %><br>
      <%= form.file_field :avatar %>
    </div>

        <div>
          <%= form.submit %>
        </div>

    <% end %>

app/views/news_articles/index.html.erb
<% if user_signed_in? %> 

 <div> <h1>Welcome <%= current_user.email %></h1> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>


<h1>News LISTS</h1>

<div class="text-primary"> Role : <%= current_user.roles.pluck(:name) %></div> 

<button><%= link_to "create new news_article",  new_news_article_path %></button>

<% @news_articles.each do |news_article|%>
    
<div class="border d-flex justify-content-center align-items-center">
<% if news_article.avatar.attached? %>
<li><%= image_tag(news_article.avatar) %></li>
<% else %>
<li>No Image Available</li>
<% end %>
<ul>
<ol>
<li><%= news_article.category.name%></li>
</ol>
<li><%= news_article.title%></li>
<li><%= news_article.sub_topic%></li>
<li><%= news_article.content%></li>

</ul>
</ol>


<button class="btn"><%= link_to "Delete", news_article_path(news_article), method: :delete, data: { turbo_method: :delete, confirm: "Are you sure?" } %></button>
<button class="btn"><%= link_to "Edit",   edit_news_article_path(news_article) %>
</button>
</div>
<% end %>

app/views/news_articles/new.html.erb
<h1>my form</h1>
<button>
<%= link_to "show news_article",  news_articles_path %></button>

<%= form_with model: @news_article do |form|%>
    <div>
    <%= form.label :Title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :Sub_topic %><br>
    <%= form.text_field :sub_topic %>
  </div>

  <div>
  <%= form.label :Content %><br>
  <%= form.text_field :content %>
</div>
<%= form.file_field :avatar %>



<div >
<%= form.label :category_id%>
<%= form.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"} %>
</div>

        <div>
         <button> <%= form.submit %></button>
        </div>

    <% end %>